### ISSUE TITLE
Parsing response for slots

### ISSUE THREAD

**Issue by Isuriv** [InsightfulSummer/alphaLib-web#23]
Need to display the title of a suggested document with three highlighted sections per slot item. Basic code is already there but need to parse the hits object being returned (data.res) so that it captures the highlighted information being returned.

Basic code for this issue is in isuri-searchbar branch but still in progress. Will update this when it's solved.

**Comment by Isuriv** [comment]
![Screenshot 2020-06-23 at 11 36 54 AM](https://user-images.githubusercontent.com/44674893/85424477-fa019500-b545-11ea-941f-301ec9c0e3a5.png)
@anewage been getting this error all morning... I want to test my slots and I don't think anything else is broken, is the server down?

**Comment by Isuriv** [comment]
![Screenshot 2020-06-23 at 1 05 22 PM](https://user-images.githubusercontent.com/44674893/85434764-874be600-b554-11ea-918b-d7f1f7333ab7.png)

I'm getting titles but trying to get top highlights

**Comment by anewage** [comment]
@Isuriv nice work. Please only post the errors and problems that are actually causing an "issue". Thanks
