### ISSUE TITLE
Word count on /analytics

### ISSUE THREAD

**Issue by anewage** [InsightfulSummer/alphaLib-web#3]
Display the word count of all of the terms inside `term_vector` for each `doc` in page _/analytics_.

The goal is to have detailed information about the frequency of terms about each document (by going to the details of that document) and the overall corpus.

**Comment by anewage** [comment]
In order to show the frequency of terms, use a table: https://vuetifyjs.com/en/components/data-tables/

**Comment by Lemos00** [comment]
![InsightIssue1](https://user-images.githubusercontent.com/55399020/84968276-189a0300-b0e4-11ea-8ac4-bfe5294a9992.jpg)
**ISSUE**
- Cannot reference data objects returned by asyncdata() function

**QUESTION**
- is it possible to use such data in the following segment
![InsightIssue1](https://user-images.githubusercontent.com/55399020/84968528-b392dd00-b0e4-11ea-932f-959678d6a694.jpg)

**Comment by anewage** [comment]
Please see the example code described in https://github.com/InsightfulSummer/alphaLib-web/pull/18#discussion_r441938726

**Comment by Lemos00** [comment]
I have added the dynamic routing functionality as requested. In the dynamic page, I also displayed the content of the document requested through its ID. Please let me know if any further changes are required so that we can merge the "Gabriel" branch. Thank you
