### ISSUE TITLE
Structured search results

### ISSUE THREAD

**Issue by anewage** [InsightfulSummer/alphaLib-web#4]
Turn the search results in page /search to a more structured, more familiar format. The title and author of the document should be visible along with the highlights from that document (max 10 from each).

**Comment by DogsAreTheShit** [comment]
`<v-card-title>{{ doc._source.meta.title }}</v-card-title>
            <v-card-subtitle>{{ doc._source.meta.author }}</v-card-subtitle>
            <v-card-subtitle>{{ doc._source.file.filename }}</v-card-subtitle>
            <v-card-subtitle>{{ doc._source.file.url }}</v-card-subtitle>`
.
.
.
`content: { number_of_fragments: 10 }`
Progress: Added author to cards, and increased max highlights to 10

Question: From what I see, title is already an implemented function but only pops up on some cards and the titles aren't always right. I don't know where 'doc._source.meta.title' is pulling info from but is this the issue coming from that code receiving the wrong info?
### **Working Title + author working as intended**
![Screen Shot 2020-06-16 at 10 43 38 PM](https://user-images.githubusercontent.com/65428292/84849212-d3fa6300-b022-11ea-9e06-27b860df8572.png)

###**no title / incorrect title**
![Screen Shot 2020-06-16 at 10 44 27 PM](https://user-images.githubusercontent.com/65428292/84849279-f2605e80-b022-11ea-9ba7-201a08e83d8e.png)

**Comment by anewage** [comment]
The documents also have the raw information as `meta.raw`. Check to see if all the documents include these fields in their `meta.raw` or not.

We have to assume a constant field and display that field. Try your best to find the best field that is shared by most of the docs. If, however still, there are missing fields, then we have to make our data "clean" and from a programming perspective there is not much to do.

PS: By more "structured", I meant something similar to Google search results. Please change the current card view to a more readable result.

**Comment by anewage** [comment]
As an example, please take a look at these:
https://vuetifyjs.com/en/components/lists/#title-with-sub-title-actions-and-action-text

**Comment by DogsAreTheShit** [comment]
just to give you an update on where I am, currently trying to use the format from [this page](https://vuetifyjs.com/en/components/lists/#title-with-sub-title-actions-and-action-text) for the existing cards but having some errors. I think theyre mostly formatting issues so im working through those

### **Errors**
![Screen Shot 2020-06-17 at 11 23 09 PM](https://user-images.githubusercontent.com/65428292/84974572-84cf3380-b0f1-11ea-97aa-8c05c900ed05.png)

**Comment by DogsAreTheShit** [comment]
I fixed the issues last night and now its displaying blank cards
![Screen Shot 2020-06-18 at 12 44 22 PM](https://user-images.githubusercontent.com/65428292/85048531-70c31a80-b161-11ea-85fb-2409a56e82ca.png)

Mete figured it out and it looks great so I've been looking through his code

**Comment by DogsAreTheShit** [comment]
I'm trying to add a chevron icon to allow the user to click for more highlights but it appears I didn't define a variable properly
### **Chevron Bottom Right of Cards**
![Screen Shot 2020-06-18 at 1 25 13 PM](https://user-images.githubusercontent.com/65428292/85052565-25ac0600-b167-11ea-9243-b1d88d77995d.png)
### **Error Message**
<img width="1067" alt="Screen Shot 2020-06-18 at 1 25 38 PM" src="https://user-images.githubusercontent.com/65428292/85052588-3492b880-b167-11ea-8226-26179a64b26e.png">

**Comment by anewage** [comment]
@DogsAreTheShit I think you need to define "show" as a data variable inside your component.
The problem, so it appears, to be related to putting a portion into the template, but not defining the proper scripts and variables to operate. If you take a look at that chevron, I think there is somewhere (either on the icon or on the button) that the code uses a variable called "show". You need to define it in your data.

**Comment by DogsAreTheShit** [comment]
I found the code I'm missing but I'm not sure where it needs to go

### **Defining "Show" Variable**
![Screen Shot 2020-06-18 at 1 44 08 PM](https://user-images.githubusercontent.com/65428292/85054281-d1565580-b169-11ea-8d36-e8f12e57978b.png)

**Comment by DogsAreTheShit** [comment]
I've looked into instance variables and it seems to behave similarly to Python using 'this.' to declare an instance variable. I am not sure if I need to use that as apart of a class so I'm experimenting with creating a search result-card class which has 'show' as an instance variable, this way also I could create instance variables for other properties like title, highlights, and have getter methods. Let me know if this is a useful feature I should implement or if there is a simpler way of making my show variable into an instance variable

**Comment by anewage** [comment]
@DogsAreTheShit 

I would highly recommend to use lists instead of cards (specifically take a look at this example: https://vuetifyjs.com/en/components/lists/#title-with-sub-title-actions-and-action-text).
Vuetify Lists are visually simpler to process and most users have already a familiarity with this representation.

I think putting too much detail in a search result would cause the user to easily be misguided. I think the proper way to implement this is to have 3 or 5 highlights for each document shown, and then if a user wants to see more, they can click on that specific card or list item and the app will take them to the document page (this means that we want to have a document page where we will display the content of the document; I will give more details on this later, but for now let's just have a page for each document where it will display only the name of the document; Gabriel is also doing something similar to this: https://github.com/InsightfulSummer/alphaLib-web/pull/18#discussion_r441938726)

**Comment by anewage** [comment]
Resolved in #19
